ALTER TABLE user_items
ADD COLUMN difficulty VARCHAR(20) NOT NULL DEFAULT 'MEDIUM', -- EASY, MEDIUM, HARD
ADD COLUMN summary TEXT NOT NULL DEFAULT '',
ADD COLUMN description TEXT DEFAULT '',
ADD COLUMN answer TEXT NOT NULL DEFAULT '',
ADD COLUMN hints TEXT DEFAULT '';